services:
  frontend:
    platform: linux/amd64
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - react_node_modules:/app/node_modules

  backend:
    build: ./backend
    env_file:
      - ./db/.env
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    env_file:
      - ./db/.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  react_node_modules:
  postgres_data: