[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.137.2",
    "sqlModel>=0.0.38",
    "psycopg[binary]>=3.3",
    "alembic>=1.13",
    "anthropic>=0.120.2",
    "dotenv>=0.9.9",
    "pymupdf>=1.28.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
