"""create_init_table

Revision ID: 24df08932870
Revises: 
Create Date: 2026-07-01 22:26:00.031931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '24df08932870'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periods',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='試験回識別子（例：R7）'),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='試験回表示名（例：令和7年度）'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='並び順'),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sort_order')
    )
    op.create_table('sections',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='試験区分識別子（例：am2）'),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='試験区分表示名（例：午前Ⅱ）'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='並び順'),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sort_order')
    )
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['period_code'], ['periods.code'], ),
    sa.ForeignKeyConstraint(['section_code'], ['sections.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_code', 'section_code', name='uix_period_section')
    )
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False, comment='問題番号'),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Markdown形式の問題文テキスト'),
    sa.Column('correct_option', sa.Integer(), nullable=False, comment='正解の選択肢（0=ア, 1=イ, 2=ウ, 3=エ）'),
    sa.CheckConstraint('correct_option between 0 and 3', name='check_correct_option'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commentaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Markdown形式の解説テキスト'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commentaries')
    op.drop_table('quizzes')
    op.drop_table('exams')
    op.drop_table('sections')
    op.drop_table('periods')
    # ### end Alembic commands ###
