"""drop options table

Revision ID: 43466a354586
Revises: d85d6924ac4d
Create Date: 2026-06-28 01:50:11.468886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '43466a354586'
down_revision: Union[str, Sequence[str], None] = 'd85d6924ac4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_options_quiz_id_correct'), table_name='options', postgresql_where='(correct_flag = true)')
    op.drop_table('options')
    op.add_column('quizzes', sa.Column('correct_option', sa.Integer(), nullable=False, comment='正解の選択肢（0=ア, 1=イ, 2=ウ, 3=エ）'))
    op.create_check_constraint('check_correct_option', 'quizzes', 'correct_option between 0 and 3')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_correct_option', 'quizzes', type_='check')
    op.drop_column('quizzes', 'correct_option')
    op.create_table('options',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False, comment='選択肢の順序（1=ア, 2=イ, 3=ウ, 4=エ）'),
    sa.Column('correct_flag', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='正解フラグ（true: 正解, false: 不正解）'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('options_quiz_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('options_pkey')),
    sa.UniqueConstraint('quiz_id', 'sort_order', name=op.f('uq_options_quiz_id_sort_order'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('uq_options_quiz_id_correct'), 'options', ['quiz_id'], unique=True, postgresql_where='(correct_flag = true)')
    # ### end Alembic commands ###
