"""drop_id_from_sections_and_periods_table

Revision ID: 9457c1dadd74
Revises: fdcbf21378ac
Create Date: 2026-07-01 12:51:14.549204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9457c1dadd74'
down_revision: Union[str, Sequence[str], None] = 'fdcbf21378ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('exams_section_id_fkey'), 'exams', type_='foreignkey')
    op.drop_constraint(op.f('exams_period_id_fkey'), 'exams', type_='foreignkey')
    op.drop_column('exams', 'period_id')
    op.drop_column('exams', 'section_id')
    
    op.drop_constraint(op.f('periods_code_key'), 'periods', type_='unique')
    op.drop_column('periods', 'id')
    op.drop_constraint(op.f('sections_code_key'), 'sections', type_='unique')
    op.drop_column('sections', 'id')
    
    op.create_primary_key('periods_pkey', 'periods', ['code'])
    op.create_primary_key('sections_pkey', 'sections', ['code'])
    
    op.add_column('exams', sa.Column('period_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('exams', sa.Column('section_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint('uix_period_section', 'exams', ['period_code', 'section_code'])
    op.create_foreign_key('exams_section_code_fkey', 'exams', 'sections', ['section_code'], ['code'])
    op.create_foreign_key('exams_period_code_fkey', 'exams', 'periods', ['period_code'], ['code'])
    
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exams_section_code_fkey', 'exams', type_='foreignkey')
    op.drop_constraint('exams_period_code_fkey', 'exams', type_='foreignkey')
    op.drop_constraint('uix_period_section', 'exams', type_='unique')
    op.drop_column('exams', 'section_code')
    op.drop_column('exams', 'period_code')
    
    op.drop_constraint('sections_pkey', 'sections', type_='primary')
    op.drop_constraint('periods_pkey', 'periods', type_='primary')
    
    op.add_column('sections', sa.Column('id', sa.INTEGER(), sa.Identity(), nullable=False))
    op.create_unique_constraint(op.f('sections_code_key'), 'sections', ['code'], postgresql_nulls_not_distinct=False)
    op.add_column('periods', sa.Column('id', sa.INTEGER(), sa.Identity(), nullable=False))
    op.create_unique_constraint(op.f('periods_code_key'), 'periods', ['code'], postgresql_nulls_not_distinct=False)
    
    op.add_column('exams', sa.Column('period_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_primary_key('periods_pkey', 'periods', ['id'])
    op.add_column('exams', sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_primary_key('sections_pkey', 'sections', ['id'])
    
    op.create_foreign_key(op.f('exams_section_id_fkey'), 'exams', 'sections', ['section_id'], ['id'])
    op.create_foreign_key(op.f('exams_period_id_fkey'), 'exams', 'periods', ['period_id'], ['id'])
    
    # ### end Alembic commands ###
