"""create init tables

Revision ID: d85d6924ac4d
Revises: 
Create Date: 2026-06-27 13:19:12.414209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd85d6924ac4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='試験回（例：令和7年度）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='試験区分（例：午前Ⅱ）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False, comment='問題番号'),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Markdown形式の問題文テキスト'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commentaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Markdown形式の解説テキスト'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_id')
    )
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='選択肢の順序（1=ア, 2=イ, 3=ウ, 4=エ）'),
    sa.Column('correct_flag', sa.Boolean(), nullable=False, comment='正解フラグ（true: 正解, false: 不正解）'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_id', 'sort_order', name='uq_options_quiz_id_sort_order')
    )
    op.create_index('uq_options_quiz_id_correct', 'options', ['quiz_id'], unique=True, postgresql_where=sa.text('correct_flag=true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_options_quiz_id_correct', table_name='options', postgresql_where=sa.text('correct_flag=true'))
    op.drop_table('options')
    op.drop_table('commentaries')
    op.drop_table('quizzes')
    op.drop_table('exams')
    op.drop_table('sections')
    op.drop_table('periods')
    # ### end Alembic commands ###
