"""add_status_to_quizzes

Revision ID: 27326435b78d
Revises: 15f88cb2a8b7
Create Date: 2026-07-04 07:35:31.404536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '27326435b78d'
down_revision: Union[str, Sequence[str], None] = '15f88cb2a8b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='draft=画像未配置, in_review=画像配置済み・レビュー待ち, published=公開中'))
    op.create_check_constraint('check_status', 'quizzes', "status in ('draft', 'in_review', 'published')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_status', 'quizzes', type_='check')
    op.drop_column('quizzes', 'status')
    # ### end Alembic commands ###
