"""add_sort_order_to_periods_and_sections

Revision ID: 3a67003b2fbe
Revises: f7edc5e98739
Create Date: 2026-07-01 01:19:26.649648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3a67003b2fbe'
down_revision: Union[str, Sequence[str], None] = 'f7edc5e98739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periods', sa.Column('sort_order', sa.Integer(), nullable=False, comment='並び順'))
    op.create_unique_constraint(None, 'periods', ['sort_order'])
    op.add_column('sections', sa.Column('sort_order', sa.Integer(), nullable=False, comment='並び順'))
    op.create_unique_constraint(None, 'sections', ['sort_order'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sections', type_='unique')
    op.drop_column('sections', 'sort_order')
    op.drop_constraint(None, 'periods', type_='unique')
    op.drop_column('periods', 'sort_order')
    # ### end Alembic commands ###
