"""add_code_to_periods_and_sections

Revision ID: f7edc5e98739
Revises: 43466a354586
Create Date: 2026-07-01 00:42:36.191381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f7edc5e98739'
down_revision: Union[str, Sequence[str], None] = '43466a354586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periods', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='試験回識別子（例：R7）'))
    op.alter_column('periods', 'name',
               existing_type=sa.VARCHAR(),
               comment='試験回表示名（例：令和7年度）',
               existing_comment='試験回（例：令和7年度）',
               existing_nullable=False)
    op.create_unique_constraint(None, 'periods', ['code'])
    op.add_column('sections', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='試験区分識別子（例：am2）'))
    op.alter_column('sections', 'name',
               existing_type=sa.VARCHAR(),
               comment='試験区分表示名（例：午前Ⅱ）',
               existing_comment='試験区分（例：午前Ⅱ）',
               existing_nullable=False)
    op.create_unique_constraint(None, 'sections', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sections', type_='unique')
    op.alter_column('sections', 'name',
               existing_type=sa.VARCHAR(),
               comment='試験区分（例：午前Ⅱ）',
               existing_comment='試験区分表示名（例：午前Ⅱ）',
               existing_nullable=False)
    op.drop_column('sections', 'code')
    op.drop_constraint(None, 'periods', type_='unique')
    op.alter_column('periods', 'name',
               existing_type=sa.VARCHAR(),
               comment='試験回（例：令和7年度）',
               existing_comment='試験回表示名（例：令和7年度）',
               existing_nullable=False)
    op.drop_column('periods', 'code')
    # ### end Alembic commands ###
